language: swift
osx_image: xcode10.2
cache:
  bundler: true
  directories:
    - vendor/bundle
    - Pods
  
before_install:

  - export LANG=en_US.UTF-8
  - brew update
  - bundle install
  
install:
  - bundle exec pod repo update
  - bundle exec pod install

before_script: 
  #- bundle exec danger 
  
script:
  - xcodebuild -workspace Buckskin.xcworkspace -scheme Buckskin -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c

# notifications:
#   email: false
#   slack: 